# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170717_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
